### ISSUE TITLE
Prioritize the user stories 

### ISSUE THREAD

**Issue by youweizeng-whu** [bazinga94/smarter-university-system#12]
Activity for #7

**Comment by bazinga94** [comment]
https://docs.google.com/spreadsheets/d/1RijVAkeGbPUf5vxSYOtJ4zACwdyqFtfCMhqO_V-sWSI/edit#gid=857985670
Rank the priority of each requirement individually

**Comment by bazinga94** [comment]
Complete setting priorities of user stories and drawing bigraph

**Comment by bazinga94** [comment]
![graphviz](https://github.com/bazinga94/smarter-university-system/assets/30291493/14f9fe08-8107-4aae-b9b8-91c6773ca36f)

updated

**Comment by hiren1407** [comment]
Done with story prioritization and drawing bigraph.

**Comment by hiren1407** [comment]
![graphviz_hiren](https://github.com/bazinga94/smarter-university-system/assets/51266216/bf0e8629-4a25-4842-b21c-211883ab1751)

**Comment by revanthreddymaturu** [comment]
Completed the prioritization and ranking. Added the bigraph code as per the template.
