### ISSUE TITLE
Statement of Work review.

### ISSUE THREAD

**Issue by bazinga94** [bazinga94/smarter-university-system#15]
Activity for #6 

Review the Statement of Work for the Smarter University System (SUS)

**Comment by youweizeng-whu** [comment]
# Class Management & Enrollment:

- Students can sign up for available classes.
- Display classes based on availability and maximum enrollment.
- Support for classes with multiple geographical locations.
- Remote video capability for students attending from remote locations.
- Immediate update on student count once a student enrolls.

# Class Discovery:​
- Logged-in students can see classes they haven't attended.​
- Display class identifiers, titles, and instructor details.​
- Link to the class syllabus page with lecture dates and topics.​
- Instructors can update syllabus information, ideally inputting data 2 months in advance.

# Notification System:

- Email notifications to administrators for classes that are 80% or more full.

# Administrator Oversight:

- Overview of all courses with current and maximum enrollment numbers.
- Ability to add or remove students from classes.
- Handle enrollment requests for students not meeting prerequisites.
- View instructor details: name, email, education, courses taught.

# Instructor Tools:

- Access to the list of enrolled students with their names and IDs.
- Support for creating and managing student teams.
- Maintain and input grades for exams, assignments, and quizzes.
- Overview of grade statistics like average, lowest, and highest grades.
- View grades of specific students throughout the semester.

# Student Tools:

- View team assignments and team members for specific classes.
- Access and view grades received throughout the semester.

**Comment by bazinga94** [comment]
# Class Management & Enrollment:

- Students can sign up for available classes.
- Display classes based on availability and maximum enrollment.
- Support for classes with multiple geographical locations.
- Remote video capability for students attending from remote locations.
- Immediate update on student count once a student enrolls.

# Class Discovery:​

- Logged-in students can see classes they haven't attended.
- Display class identifiers, titles, and instructor details.
- Link to the class syllabus page with lecture dates and topics.
- Instructors can update syllabus information, ideally inputting data 2 months in advance.

# Notification System:

- Email notifications to administrators for classes that are 80% or more full.

# Administrator Oversight:

- Administrators can check the overview of all courses with current and maximum enrollment numbers.
- Administrators have the ability to add or remove students from classes.
- Students who do not meet prerequisites can submit an enrollment request to both administrators and instructors
- Administrators and instructors should handle enrollment requests from students not meeting prerequisites.
- Administrators can search instructor details: name, email, education, and courses taught.

# Instructor Tools:

- Instructors can access the list of enrolled students with their names and IDs.
- Instructors and TAs can assign and name the student groups.
- Instructors and TAs can maintain and input grades for exams, assignments, and quizzes.
- Instructors and TAs can overview grade statistics like average, lowest, and highest grade statistics.
- Instructors and TAs can check the grades of specific students throughout the semester.

# Student Tools:

- Check team assignments and team members for specific classes.
- Access and view grades received throughout the semester.

==================================
_Added more details._

**Comment by youweizeng-whu** [comment]
A great work! I think we can move on to the next part: find epics and group the requirements into different epic.
