### ISSUE TITLE
Create API test cases

### ISSUE THREAD

**Issue by saroi** [bazinga94/smarter-university-system#30]
Activity for #8

**Comment by saroi** [comment]
Created spreadsheet for creating test cases for smarter university system

**Comment by bazinga94** [comment]
<img width="637" alt="image" src="https://github.com/bazinga94/smarter-university-system/assets/30291493/a0199557-51e6-42e5-b7db-fb013ef99b90">

And according to the PDF Task 5, says to use category partition and boundary value analysis. 
In the case of category partition, shouldn't there be a valid/invalid partition? 
And to use boundary value analysis, for example, I think we should also add cases -91, -90, -89, 89, 90, 91 / -181, -180, -179, 179, 180, and 181 for "lat" and "lon" parameters, respectively.

**Comment by revanthreddymaturu** [comment]
While writing some API test cases, I found that we misinterpreted the flag values. We did not cover the positive scenarios for the plag parameters. From what I see, the flag values are misinterpreted, and the values seem incorrect. Let's try to rewrite them in the correct way.
